name: todone
description: Analyze your TODOs in code and create a summary

inputs:
  globs:
    description: "Files to analyze, glob patterns supported"
    required: false
    default: "**/*"
  github-token:
    description: "GitHub token to access the repository"
    required: false
    default: "${{ github.token }}"
  create-issues:
    description: "Create issues for TODOs found in the code"
    required: false
    default: "true"

runs:
  using: "node24"
  main: "dist/bin.js"
